version: '3.8'

services:
  frontend:
    build:
      context: ./client
    container_name: quickblog-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - quickblog-network

  backend:
    build:
      context: ./Backend
    container_name: quickblog-backend
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:password@mongodb:27017/quickblog?authSource=admin
      JWT_SECRET: secret123
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - quickblog-network

  mongodb:
    image: mongo:6
    container_name: quickblog-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - quickblog-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: quickblog-jenkins
    user: root
    ports:
      - "8085:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - quickblog-network

networks:
  quickblog-network:
    driver: bridge

volumes:
  mongodb_data:
  jenkins_data: